# Log Application
logging:
  file: spring-logs/desafio.log
  
spring:

  # Datasource
  datasource:
    continue-on-error: true
    data: classpath:/dml.sql
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    password: postgres
    platform: postgresql
    #schema: classpath:/schema.sql
    url: jdbc:postgresql://localhost:5432/desafio
    username: postgres

  # Domain 
  jmx:
    default-domain: desafio

  # JPA 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true

  # Path for Views MVC
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  # Ansi Output for Console
  output:
    ansi:
      enabled: always
